/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.libreria;

import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lilia
 */
public class Compras extends javax.swing.JFrame {
//    String nombreImagen="";
//    ImageIcon  Imagen[]=new ImageIcon[39];
//    int contador=1;
    
    

    /**
     * Creates new form Compras
     */
    public Compras() {
        initComponents();
        llenarTabla();
        this.setResizable(false);
        this.setSize(725,690);
        this.setLocationRelativeTo(this);
        unidadesDisponibles.setEnabled(false);
        this.setDefaultCloseOperation(2);  
        
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cod = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        fotoLibro = new javax.swing.JLabel();
        Cambio = new javax.swing.JTextField();
        nombrelibro = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        ISBN = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        cantidad = new javax.swing.JLabel();
        dineroIngresado = new javax.swing.JTextField();
        Unidades = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        unidadesDisponibles = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        Buscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Libros.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel1.setText("Confirmación de compra");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 270, 40));

        cod.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cod.setText("ISBN:");
        jPanel1.add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 60, 20));

        precio1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        precio1.setText("Precio:");
        jPanel1.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        dinero.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        dinero.setText("Dinero ingresado:");
        jPanel1.add(dinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cambio.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cambio.setText("Cambio:");
        jPanel1.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnTotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        jPanel1.add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 100, 40));

        fotoLibro.setOpaque(true);
        jPanel1.add(fotoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 200, 220));

        Cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioActionPerformed(evt);
            }
        });
        jPanel1.add(Cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 170, -1));
        jPanel1.add(nombrelibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 220, -1));
        jPanel1.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 210, -1));
        jPanel1.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 190, -1));

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaLibros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 590, 270));
        jPanel1.add(ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 210, -1));

        btnConfirmar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 40));

        cantidad.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        cantidad.setText("Cantidad:");
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel1.add(dineroIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 180, -1));

        Unidades.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        Unidades.setText("Unidades disponibles: ");
        jPanel1.add(Unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 170, 20));

        Titulo2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        Titulo2.setText("Título:");
        jPanel1.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 20));
        jPanel1.add(unidadesDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 90, -1));

        btnCancelar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, 40));

        btnCargar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, 40));

        Buscar.setText("Buscar libro");
        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarKeyReleased(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 190, -1));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 30));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Libros.jpg"))); // NOI18N
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 700));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double total, precioLibro, dineroIng;
        int cant, cantExistencia, cantRestante;
        precioLibro=Double.parseDouble(Precio.getText());
        cant=Integer.parseInt(Cantidad.getText());
        cantExistencia=Integer.parseInt(unidadesDisponibles.getText());
                if (cantExistencia<=0) {
          JOptionPane.showMessageDialog(null,"El libro no está disponible","Error",JOptionPane.WARNING_MESSAGE);
          btnConfirmar.setEnabled(false);
        }
                if (cant<=0) {
        JOptionPane.showMessageDialog(null,"No puedes tener menos de un libro","Error",JOptionPane.WARNING_MESSAGE); 
                }
                else {            
        dineroIng=Double.parseDouble(dineroIngresado.getText());
        if (dineroIng>=(precioLibro*cant)) {
        total=dineroIng-(precioLibro*cant);
        Cambio.setText(String.valueOf(total));
        cantRestante=cantExistencia-cant;
        if (cantRestante<=0) {
          JOptionPane.showMessageDialog(null,"Ya no hay suficientes libros","Error",JOptionPane.WARNING_MESSAGE);
           btnConfirmar.setEnabled(false);
        }
        else {
        unidadesDisponibles.setText(String.valueOf(cantRestante));
        }
        }
        else {
         JOptionPane.showMessageDialog(null,"No puedes ingresar una cantidad menor al precio del libro","Error",JOptionPane.WARNING_MESSAGE); 
                }
                }
                       
    }//GEN-LAST:event_btnTotalActionPerformed

    private void tablaLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibrosMouseClicked
       if(evt.getButton()==1) {
            int fila=tablaLibros.getSelectedRow();
            ISBN.setText(tablaLibros.getValueAt(fila,0).toString());
            nombrelibro.setText(tablaLibros.getValueAt(fila, 1).toString());
            Precio.setText(tablaLibros.getValueAt(fila, 2).toString());
            Cantidad.setText(tablaLibros.getValueAt(fila,3).toString());
            unidadesDisponibles.setText(tablaLibros.getValueAt(fila,4).toString());
    }
    }//GEN-LAST:event_tablaLibrosMouseClicked

    private void CambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioActionPerformed

        
    }//GEN-LAST:event_CambioActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
            guardarCompra();
            guardarVenta();
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG & GIF Images","jpg","gif");
        JFileChooser FC = new JFileChooser();
        FC.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FC.setDialogTitle("Abrir archivo");
        File ruta = new File("C:\\Users\\lilia\\OneDrive\\Documentos\\Tecnológico\\Sexto semestre\\Libreria\\src\\main\\resources\\imagenes");
        FC.setCurrentDirectory(ruta);
        int resultado= FC.showOpenDialog(this);
        if (resultado!= JFileChooser.CANCEL_OPTION) {
            File nombreArchivo = FC.getSelectedFile();
            String nombreImagen = String.valueOf(nombreArchivo);
            Image foto = getToolkit().getImage(nombreImagen);
            foto=foto.getScaledInstance(fotoLibro.getWidth(), fotoLibro.getHeight(), Image.SCALE_DEFAULT);
            fotoLibro.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyReleased
        Conexiones con = new Conexiones();
        con.BuscarLibro(Buscar.getText(),tablaLibros);
    }//GEN-LAST:event_BuscarKeyReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    void llenarTabla() {
        Conexiones tbl = new Conexiones();
        tbl.mostrarTabla(tablaLibros);
    }
    
    void limpiar() {
         nombrelibro.setText("");
         Precio.setText("");
         Cantidad.setText("");
         Cambio.setText("");
         fotoLibro.setIcon(null);
         dineroIngresado.setText("");             
    }
        void guardarCompra () {
            if (verificar()) {        
               Libreria lib = new Libreria();
               lib.setCantidad(Integer.parseInt(Cantidad.getText()));
               lib.setCantidadEnExistencia(Integer.parseInt(unidadesDisponibles.getText()));
               lib.setIsbn(ISBN.getText()); 
               new Conexiones().ActualizarRegistro(lib);
               llenarTabla();
     }
        } 
        
        void guardarVenta () {
            if (verificar()) {        
               Libreria lib = new Libreria();
               lib.setIsbn(ISBN.getText());
               lib.setTítulo(nombrelibro.getText());
               lib.setPrecio(Float.parseFloat(Precio.getText()));
               lib.setCantidad(Integer.parseInt(Cantidad.getText()));
                try {
                    new Conexiones().RegistroVenta(lib);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
                }
               limpiar();
               llenarTabla();
     }
        }
    
    boolean verificar() {
        if(nombrelibro.getText().isEmpty() || Precio.getText().isEmpty()
                || Cantidad.getText().isEmpty() || Cambio.getText().isEmpty()) //|| fotoLibro.getIcon()==null)
                {
            JOptionPane.showMessageDialog(null,"Debes llenar todos los datos","Error",JOptionPane.WARNING_MESSAGE);
            return false;
        } else 
            
            return true; 
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JTextField Cambio;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField Precio;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Unidades;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel cambio;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel cod;
    private javax.swing.JLabel dinero;
    private javax.swing.JTextField dineroIngresado;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    public static javax.swing.JLabel fotoLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrelibro;
    private javax.swing.JLabel precio1;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTextField unidadesDisponibles;
    // End of variables declaration//GEN-END:variables
}
