/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.libreria;

import java.text.SimpleDateFormat;

/**
 *
 * @author lilia
 */
public class PreOrdenar extends javax.swing.JFrame {

    /**
     * Creates new form PreOrdenar
     */
    public PreOrdenar() {
        initComponents();
        jCalendar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        títuloLibro = new javax.swing.JTextField();
        títuloLibro1 = new javax.swing.JTextField();
        títuloLibro2 = new javax.swing.JTextField();
        títuloLibro3 = new javax.swing.JTextField();
        btnHecho = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fechaSalida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        títuloLibro5 = new javax.swing.JTextField();
        jCalendar = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        Titulo.setText("Pre-ordenar");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel3.setText("Número de cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 40));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel4.setText("Autor/a del libro:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel2.setText("Fecha en la que sale:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 40));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel5.setText("Género:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 40));
        jPanel1.add(títuloLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 310, -1));

        títuloLibro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                títuloLibro1MouseClicked(evt);
            }
        });
        jPanel1.add(títuloLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 310, -1));
        jPanel1.add(títuloLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 310, -1));
        jPanel1.add(títuloLibro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 310, -1));

        btnHecho.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnHecho.setText("Confirmar");
        btnHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHechoActionPerformed(evt);
            }
        });
        jPanel1.add(btnHecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel6.setText("Nombre del libro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 40));

        fechaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaSalidaMouseClicked(evt);
            }
        });
        jPanel1.add(fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 310, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel7.setText("Nombre del cliente:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, 40));
        jPanel1.add(títuloLibro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 310, -1));

        jCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarPropertyChange(evt);
            }
        });
        jPanel1.add(jCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHechoActionPerformed
//        boolean b = false;
//        if(verificar()) {
//            try {
//                b = new Conexiones().SiExiste(títuloLibro.getText());
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(EncargarLibro.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            if (b) {
//                JOptionPane.showMessageDialog(null,"Ese libro ya está encargado","Error",JOptionPane.INFORMATION_MESSAGE);
//            }
//            else {
//                Libreria lib = new Libreria();
//                lib.setTítulo(títuloLibro.getText());
//                lib.setAutor(autorLibro.getText());
//                lib.setGénero(géneroLibro.getText());
//
//                try {
//                    new Conexiones().RegistroNuevo(lib);
//                } catch (FileNotFoundException ex) {
//                    Logger.getLogger(EncargarLibro.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                limpiar();
//            }
//        }
    }//GEN-LAST:event_btnHechoActionPerformed

    private void títuloLibro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_títuloLibro1MouseClicked
       
    }//GEN-LAST:event_títuloLibro1MouseClicked

    private void fechaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaSalidaMouseClicked
        jCalendar.setVisible(true);
    }//GEN-LAST:event_fechaSalidaMouseClicked

    private void jCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarPropertyChange
        if(evt.getOldValue() != null) {
            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
            fechaSalida.setText(fecha.format(jCalendar.getCalendar().getTime()));
                    
        }
    }//GEN-LAST:event_jCalendarPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreOrdenar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnHecho;
    private javax.swing.JTextField fechaSalida;
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField títuloLibro;
    private javax.swing.JTextField títuloLibro1;
    private javax.swing.JTextField títuloLibro2;
    private javax.swing.JTextField títuloLibro3;
    private javax.swing.JTextField títuloLibro5;
    // End of variables declaration//GEN-END:variables
}
